[package]
name = "raildata"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
edition = "2018"

[[bin]]
name = "raildata"
doc = false

[dependencies]
bincode		= "1.1.3"
crossbeam       = "0.7.3"
derive_more     = "0.14.0"
osmxml          = { git = "https://github.com/partim/osmxml.git" }
url             = "1.2"
ignore          = "0.2"
radix_trie	= { version = "0.2", features = ["serde"] }
rayon           = "1.0.1"
serde 		= { version = "1.0", features = ["derive"] }
unicode-normalization = "0.1.13"
yaml-rust	= "0.4.4"

