[package]
name = "raildata"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[[bin]]
name = "raildata"
doc = false

[dependencies]
crossbeam       = "0.2.12"
derive_more     = "0.14.0"
osmxml          = { git = "https://github.com/partim/osmxml.git" }
url             = "1.2"
ignore          = "0.2"
rayon           = "1.0.1"
yaml-rust       = { git = "https://github.com/partim/yaml-rust.git", branch="pub-marker" }

